name: CI/CD Pipeline Inmutable (GitHub Packages + Java Buildpacks)

on:
  push:
    branches: [ "main" ]

permissions:
  contents: write
  pull-requests: write
  packages: write

jobs:
  release-or-deploy:
    runs-on: ubuntu-latest
    steps:
      # 1. Ejecutar Release Please para automatizar versiones (Configurado para Maven)
      - uses: googleapis/release-please-action@v4
        id: release
        with:
          release-type: maven # <-- CORREGIDO: Ahora entiende proyectos Java/Maven

      # 2. Descargar el código (solo si se aceptó el PR de la nueva release)
      - name: Checkout del código
        if: ${{ steps.release.outputs.release_created }}
        uses: actions/checkout@v4

      # 3. Configurar Java para que corra el Buildpack
      - name: Configurar JDK 26
        if: ${{ steps.release.outputs.release_created }}
        uses: actions/setup-java@v4
        with:
          java-version: '26'
          distribution: 'temurin'
          cache: 'maven'

      # 4. Autenticación en GHCR
      - name: Autenticación en GHCR
        if: ${{ steps.release.outputs.release_created }}
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # 5. Construir y subir la imagen usando Cloud-Native Buildpacks
      - name: Construir y Publicar con Buildpacks
        if: ${{ steps.release.outputs.release_created }}
        run: |
          BASE_IMAGE_NAME=$(echo "ghcr.io/${{ github.repository }}" | tr '[:upper:]' '[:lower:]')
          
          # CAMBIAMOS 'tag_name' POR 'version' PARA QUITAR LA 'v' ASQUEROSA
          VERSION_LIMPIA="${{ steps.release.outputs.version }}"
          
          echo "Construyendo contenedores inmutables para la versión: $VERSION_LIMPIA"
          
          ./mvnw spring-boot:build-image \
            -Dspring-boot.build-image.imageName=$BASE_IMAGE_NAME:$VERSION_LIMPIA,$BASE_IMAGE_NAME:${{ github.sha }},$BASE_IMAGE_NAME:latest \
            -Dspring-boot.build-image.publish=true \
            -Dspring-boot.build-image.publishRegistry.username=${{ github.repository_owner }} \
            -Dspring-boot.build-image.publishRegistry.password=${{ secrets.GITHUB_TOKEN }}