name: CI/CD Spring Boot con Buildpacks (Docker Hub + Release Please)

on:
  push:
    branches: [ "main" ]

# Importante: Release Please necesita estos permisos para poder gestionar las Pull Requests y las Releases
permissions:
  contents: write
  pull-requests: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    # Paso 1: Ejecutar Release Please para automatizar el Changelog y versiones en Maven
    - uses: googleapis/release-please-action@v4
      id: release
      with:
        release-type: maven # <-- Configurado para rastrear y actualizar tu pom.xml de Java

    # Paso 2: Descargar el código fuente (Solo si Release Please detectó que se aceptó una versión oficial)
    - name: Descargar código
      if: ${{ steps.release.outputs.release_created }}
      uses: actions/checkout@v4

    # Paso 3: Configurar Java
    - name: Configurar JDK 26
      if: ${{ steps.release.outputs.release_created }}
      uses: actions/setup-java@v4
      with:
        java-version: '26'
        distribution: 'temurin'
        cache: 'maven'

    # Paso 4: Iniciar sesión en Docker Hub de forma segura
    - name: Iniciar sesión en Docker Hub
      if: ${{ steps.release.outputs.release_created }}
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    # Paso 5: Ejecutar Buildpack usando el Tag generado por Release Please
    - name: Construir y Publicar Imagen con Buildpacks
      if: ${{ steps.release.outputs.release_created }}
      run: |
        # Extraemos la versión limpia generada por Release Please (ej: 1.0.0)
        TAG_NAME="${{ steps.release.outputs.tag_name }}"
        echo "La nueva versión oficial en Docker Hub será: $TAG_NAME"
        
        # Buildpack empaqueta y sube tanto la versión inmutable como el 'latest' y el hash de git
        ./mvnw spring-boot:build-image \
          -Dspring-boot.build-image.imageName=docker.io/${{ secrets.DOCKERHUB_USERNAME }}/demo-buildpacks:$TAG_NAME,docker.io/${{ secrets.DOCKERHUB_USERNAME }}/demo-buildpacks:${{ github.sha }},docker.io/${{ secrets.DOCKERHUB_USERNAME }}/demo-buildpacks:latest \
          -Dspring-boot.build-image.publish=true